// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Items(arg1:string,arg2:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Reserve(arg1:string,arg2:string,arg3:string):Promise<boolean>;
