// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Devices(arg1, arg2) {
  return window['go']['main']['V7yzfmPN']['Devices'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['V7yzfmPN']['Login'](arg1, arg2);
}

export function Reserve(arg1, arg2, arg3) {
  return window['go']['main']['V7yzfmPN']['Reserve'](arg1, arg2, arg3);
}
